name: baystat
channels:
  - conda-forge

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - pip
  - matplotlib
  - ipywidgets
  - scipy
  - pandas
  - numba
  - numpy

  - seaborn
  - plotly
  - ipython

  - pytest
  - pytest-cov




